name: GUIServerSelector
version: @version@
main: com.github.highright1234.guiserverselector.GUIServerSelector
api-version: 1.17
depend:
  - InventoryGUI
commands:
  GuiServerSelector:
    description: GUIServerSelector Command
    usage: /GUIServerSelector
    aliases: gss